use bevy::prelude::*;
use blenvy::*;

pub struct BlenvyInitializerPlugin;

impl Plugin for BlenvyInitializerPlugin {
    fn build(&self, app: &mut App) {
        app
            // Register all components as reflectable to be able to use them in the blender plugin
            .add_systems(Startup, setup)
            .add_plugins(BlenvyPlugin::default());
    }
}

fn setup(mut commands: Commands) {
    commands.spawn((
        // Will be generated by the Blenvy plugin in Blender on save
        BlueprintInfo::from_path("levels/World.glb"),
        SpawnBlueprint,
        HideUntilReady,
        GameWorldTag,
    ));
}
